home:
    path: /
    controller: App\Controller\HomeController::home

register :
    path: /auth/register/
    controller: App\Controller\AuthController::registerView

login :
    path: /auth/login/
    controller: App\Controller\LoginController::loginView

logout :
    path: /auth/logout/
    controller: App\Controller\LoginController::logout

admin :
    path: /auth/admin/
    controller: App\Controller\AdminController::view

viewByOne :
    path: /auth/viewbyone/{id}
    controller: App\Controller\AdminController::viewbyone

deleteOne :
    path: /auth/deleteone/{id}
    controller: App\Controller\AdminController::deleteOne

updateOne :
    path: /auth/updateone/{id}
    controller: App\Controller\AdminController::updateOne

postUpdateOne :
    path: /auth/postupdateone/{id}
    controller: App\Controller\AdminController::postUpdateOne
    methods: POST

postGenre :
    path: /auth/postgenre/
    controller: App\Controller\AdminController::creategenre
    methods: POST

postFilm:
    path: /auth/postfilm/
    controller: App\Controller\AdminController::createfilm
    methods: POST

moreDetails:
    path: /home/moredetails/{id}
    controller: App\Controller\CinemaController::moreDetails

cinema :
    path: /home/cinema/
    controller: App\Controller\CinemaController::cinemaView

espace :
    path: /auth/espace/
    controller: App\Controller\EspaceController::espaceView

camera :
    path: /home/camera/
    controller: App\Controller\CameraController::surprise

postRegister:
    path: auth/postregister/
    controller: App\Controller\AuthController::createmember
    methods: POST

postLogin:
    path: auth/postLogin/
    controller: App\Controller\LoginController::postLogin
    methods: POST

